### ISSUE TITLE
When using ::find or ::findOrFail on models, entries are loaded even if the structure id does not match

### ISSUE THREAD

**Issue by olavoyen** [apility/netflex-sdk#117]
**Describe the bug**
When using models to load an entry via find or findOrFail static functions you are able to get the entry even if the structure id of the entry you are loading does not match the model you are loading it through. This creates getters and setters that writes or returns wrong data and could by worst case expose sensitive data. This also creates wrong structure in the cached data of the entry when loaded through the wrong model.

**To Reproduce**
Try loading an entry through a model with $directory set to other than the entry you are loaded.

**Expected behavior**
Model should return null (find) or Exception (findOrFail) if the structure id of the loaded entry does not match the structure id of the model. The resolve static function should also be tested.

**Comment by thomas-alrek** [comment]
Fixed in 518aedeeedc8ef567d7d24bead48f3132c2947ae
