### ISSUE TITLE
Wrong return value in doc block for get_static_content 

### ISSUE THREAD

**Issue by cathrinevaage** [apility/netflex-sdk#12]
**Describe the bug**
The [return value](https://github.com/apility/netflex-sdk/blob/7949d42/src/functions/common/functions_templates.php#L47) set in `get_static_contents` doc block is wrong.
It is set to `void`, but should probably be `mixed`.

**Additionally**
The description should probably be updated to something a bit more descriptive.

**Comment by thomas-alrek** [comment]
Fixed in f6883e645b8cc9bcdf7f75a58992b82b802b465a
