### ISSUE TITLE
Netflex\Structure::findOrFail should point to static::find

### ISSUE THREAD

**Issue by cathrinevaage** [apility/netflex-sdk#15]
[`Netflex\Structure::findOrFail`](https://github.com/apility/netflex-sdk/blob/751677b39549031c67791266cd4b62c38c8f3f4d/src/model/Structure.php#L329) uses [`self::find`](https://github.com/apility/netflex-sdk/blob/751677b39549031c67791266cd4b62c38c8f3f4d/src/model/Structure.php#L331), when it should say `static::find`.

This is to allow overriding of `find` in subclasses, without also having to override `findOrFail`.

**Comment by cathrinevaage** [comment]
**Additionally**
`findOrFail` should also have doc blocks saying what it throws.

**Comment by thomas-alrek** [comment]
Fixed in commit 14da6d8b6e6f2b6eeca55795f1aae3b8dfd6377b
