### ISSUE TITLE
$resolutions parameter in get_block_content_image is not used

### ISSUE THREAD

**Issue by cathrinevaage** [apility/netflex-sdk#28]
[`get_block_content_image`](https://github.com/apility/netflex-sdk/blob/32ef200/src/functions/common/functions_blocks.php#L156) has the parameter `$resolutions`, but it's never used.

This is a problem because we can't support retina displays when using this function.

**Comment by thomas-alrek** [comment]
This will be fixed later, as the internals of the various image helpers are being refactored to all use the same method for generating markup.
