### ISSUE TITLE
 symbol in get_page_content_image in editor

### ISSUE THREAD

**Issue by erikdju** [apility/netflex-sdk#32]
**Describe the bug**
There's a  (Apple) symbol in the markup generated by `get_page_content_image()` in the editor. 

**Expected behavior**
There should not be a  (Apple) symbol in the markup.

**Additional context**
[src/functions/editor/functions_pages.php#L189](https://github.com/apility/netflex-sdk/blob/3b978dd4b5dcf09aca26585e94975bf6d7a976ec/src/functions/editor/functions_pages.php#L189)

**Comment by thomas-alrek** [comment]
Fixed in 05fdacf8705a8e57617590355139e0a0642d408d
