### ISSUE TITLE
Randomize default cache lifetime

### ISSUE THREAD

**Issue by olavoyen** [apility/netflex-sdk#63]
To distribute requests to the api, the cache time on all cached items should be set to a random number between 3500 and 3800. At the same time. it should also be possible to overwrite this interval in the site config.

Should be written into the Cache class as a default, and 3600 should be removed from all cache->save in the sdk.

**Comment by thomas-alrek** [comment]
Fixed in 73a6262afc9b262f17e1dbf81ba49f7f2246ec95
